#include "VertexShaderInput.hlsl"
#include "ShaderConstant.hlsl"

Define_TransformWVP_HLSL(0);

#define DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION3(VS_INPUT)\
	float4 vs_main_##VS_INPUT(VS_INPUT input) : SV_POSITION\
	{\
		return mul(float4(input.position.xyz, 1.0), wvp);\
	}

#define DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION4(VS_INPUT)\
	float4 vs_main_##VS_INPUT(VS_INPUT input) : SV_POSITION\
	{\
		return mul(input.position, wvp);\
	}



DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION3(Position3);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION3(Position3Normal3);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION3(Position3Normal4);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION3(Position3UV2);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION3(Position3UV2Normal3);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION3(Position3UV2Normal4);

DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION4(Position4);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION4(Position4Normal3);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION4(Position4Normal4);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION4(Position4UV2);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION4(Position4UV2Normal3);
DEFINE_DEPTH_PASS_VS_ENTRY_POINT_POSITION4(Position4UV2Normal4);
