#ifndef VERTEX_SHADER_INPUT_H
#define VERTEX_SHADER_INPUT_H





#define DEFINE_VS_INPUT_POSITION_(DIM, POSITION)\
struct Position##DIM\
{\
	float##DIM position##POSITION;\
}

#define DEFINE_VS_INPUT_POSITION_UV_(P_DIM, U_DIM, POSITION, TEXCOORD)\
struct Position##P_DIM##UV##U_DIM\
{\
	float##P_DIM position##POSITION;\
	float##U_DIM uv##TEXCOORD;\
}

#define DEFINE_VS_INPUT_POSITION_NORMAL_(P_DIM, N_DIM, POSITION, NORMAL)\
struct Position##P_DIM##Normal##N_DIM\
{\
	float##P_DIM position##POSITION;\
	float##N_DIM normal##NORMAL;\
}

#define DEFINE_VS_INPUT_POSITION_UV_NORMAL_(P_DIM, U_DIM, N_DIM, POSITION, TEXCOORD, NORMAL)\
struct Position##P_DIM##UV##U_DIM##Normal##N_DIM\
{\
	float##P_DIM position##POSITION;\
	float##U_DIM uv##TEXCOORD;\
	float##N_DIM normal##NORMAL;\
}

#define DEFINE_VS_INPUT(POSITION, TEXCOORD, NORMAL)\
	DEFINE_VS_INPUT_POSITION_(3, POSITION);\
	DEFINE_VS_INPUT_POSITION_(4, POSITION);\
	DEFINE_VS_INPUT_POSITION_UV_(3, 2, POSITION, TEXCOORD);\
	DEFINE_VS_INPUT_POSITION_UV_(4, 2, POSITION, TEXCOORD);\
	DEFINE_VS_INPUT_POSITION_NORMAL_(3, 3, POSITION, NORMAL);\
	DEFINE_VS_INPUT_POSITION_NORMAL_(3, 4, POSITION, NORMAL);\
	DEFINE_VS_INPUT_POSITION_NORMAL_(4, 3, POSITION, NORMAL);\
	DEFINE_VS_INPUT_POSITION_NORMAL_(4, 4, POSITION, NORMAL);\
	DEFINE_VS_INPUT_POSITION_UV_NORMAL_(3, 2, 3, POSITION, TEXCOORD, NORMAL);\
	DEFINE_VS_INPUT_POSITION_UV_NORMAL_(3, 2, 4, POSITION, TEXCOORD, NORMAL);\
	DEFINE_VS_INPUT_POSITION_UV_NORMAL_(4, 2, 3, POSITION, TEXCOORD, NORMAL);\
	DEFINE_VS_INPUT_POSITION_UV_NORMAL_(4, 2, 4, POSITION, TEXCOORD, NORMAL)





#endif
